### ISSUE TITLE
如何处理噪音？

### ISSUE THREAD

**Issue by kaiery** [red5pro/streaming-android#10]
使用 two way的时候，如何抑制噪音？

**Comment by cameroninfrared5** [comment]
Hi Kaiery,

Based off of google Translate your question is:
When using two way , how to suppress the noise?


Currently we don't support Echo Cancellation on Android - iOS is supported, but Android is still in the works here at Infrared5. We're hoping to crack this egg soon.

**Comment by cameroninfrared5** [comment]
Hello!

Great news - we're finally ready to release a huge update for our server / sdk. We haven't announced this release officially yet but we're giving you early access to it. Please give it a try and let us know how it works for ya! 

Requirement: To use these new SDKs you MUST install the new server as well. Major refactoring going on with this release, so the server and SDKs are required.

Grab the New Versions Here:
Android: https://account.red5pro.com/download/stream_android
iOS: https://account.red5pro.com/download/stream_ios
Server: https://account.red5pro.com/download/red5


iOS:

- Crash fixes
- Sample Rate controls added (? maybe not make public knowledge yet) Ha!
- Small memory cleanup
- Fixed volume bug 
- Major performance updates
- Multiple crash fixes

Android:

- Acoustic Echo Cancellation Support
- Fixes for R5Configuration buffer time not being respected
- Packet flagging corrected for key-frame markers (artifacting)
- Muxer fixes for timestamps
- Arm64 libraries added 
- Fixed Galaxy S6 Crashing Bug (due to its encoder and issues with the 32 bit emulator)
- R5AudioController added
- Fixed volume bug 
- Major performance updates
- Multiple crash fixes

Server Release Notes:

- Bug fix for Null meta data - ffmpeg bug in rtmp publishing
- Fixed unable to record
- Fixed restream errors related to strict amf0
- Fixed AAC sample rate handling
- Improved HLS reliability
- Fixed HLS streams with audio only
- Improved HLS timestamps and memory management 
- Fixed core bug for mobile subscribers not calling stream playback security
- Fixed bug for round robin clustering in autoscaled appliances.
- Removed Servlet dependencies
- Hardened fix for concurrency
- Added more verbose logging
- Fixed room name issue with using very long names in clustering
- Fixed rare Nullpointer exception at startup
- Fixed some artifacting with FLV recording
- Fixed append and record
- Cleanup to queuing too many packets during rebuffering
- 

Known Issues:

- Camera Swap - If device only has one camera built in camera swap example will crash due to the device only having one camera
- Echo Cancellation:
- Certain devices may experience background static with this version when you are testing two way communication in close proximity:
- S6
- S3

iOS:

Known Issues:

- No known issues

Best,
-Cameron
