### ISSUE TITLE
TwoWay - echo cancellation not working

### ISSUE THREAD

**Issue by Panzenbaby** [red5pro/streaming-android#169]
Hey there. All the time I get some annoying echo when doin a two way stream. I checked the documentations which says that I have to use the same R5AudioController for publish ans subscribe stream. So I passed the same instance to both (it's already a singleton but I wanted to be sure). Plus I set the audio bitrate to 8000 which I also had from the documentation. But the AEC is still not working. I checked your sample "TwoWayTest" where AEC seems to not be working too.
Could you please have a look on this? Am I missing something or is this a bug?

**Comment by beetlejesss** [comment]
@Panzenbaby echo cancellation is variable in Android devices because there is no hardware standard -both in their echo cancellation support and also in the placement of the earpiece relative to the microphone. Some devices will work very well, and others not at all. Unfortunately, all we can recommend is that you use headphones if you want to run two-way on Android.

**Comment by Panzenbaby** [comment]
Sorry but you are litte to easy with this. I'm testing on a Pixel 4 wich definitely supports  AcousticEchoCanceling. I've checked this by AcousticEchoCanceler.isAvailable which returned true.
