### ISSUE TITLE
Live streaming connected but not playing on Red5 Pro Server

### ISSUE THREAD

**Issue by shankar667** [red5pro/streaming-android#42]
Hi,
i am using android example when i stream (publish) from mobile to Red5 Pro Server(local), it showing incoming steams but not playing when i click on URL, I am also tried using jwplayer (RTMP) no streaming works,
can you please suggest, anything missing?

**Comment by beetlejesss** [comment]
In the top right corner of the Red5 Pro server home page (http://localhost:5080), make sure that "Your server IP address is: " is set to the same IP address that you are publishing to via mobile (by default it may be showing your wired IP instead of your wireless). This will propagate the IP to the subscribe.jsp page and the link should work.
Also - there is a publishing bug with some Android Marshmallow devices that we will be addressing in the next SDK release (by end of September), so this may also be the problem.
