### ISSUE TITLE
twoway中，只开启一个客户端，等待几分钟后，出现异常

### ISSUE THREAD

**Issue by kaiery** [red5pro/streaming-android#9]
twoway中，只开启一个客户端，等待几分钟后，出现异常

![image](https://cloud.githubusercontent.com/assets/10444022/11917303/e22702ba-a73c-11e5-8580-90d9cd9f2071.png)

**Comment by cameroninfrared5** [comment]
Hi Kaiery,

Your Question Per Google Translate:
twoway , only open a client , after waiting a few minutes , abnormal
twoway中，只开启一个客户端，等待几分钟后，出现异常

We'll be able to better assist you with your questions if you can send us an email VIA the support contact information on our red5pro.com site so we can work with you one on one and help better understand where the issue is stemming from.
